---
# tasks file for ec2_k8s_master
  - name: "Install docker"
    package:
            name: docker
            state: present
  - name: "Start docker service"
    service:
            name: "docker"
            state: started
            enabled: yes

  - name: "Configure yum for k8s"
    yum_repository:
         name: Kubernetes
         description: "RPM of k8s"
         file: kubernetes
         baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
         enabled: yes
         gpgcheck: yes
         gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
         state: present

  - name: "Install kubelet , Kubeadm, kubectl, ip-route"
    package:
            name: "{{ item }}"
            state: present
    loop:
      - kubectl
      - kubeadm
      - kubelet
      - iproute-tc

  - name: "Start kubelet service"
    service:
            name: "kubelet"
            state: started
            enabled: yes

  - name: "change docker driver to systemd"
    copy:
            content: |
                      {
                       "exec-opts": ["native.cgroupdriver=systemd"]
                            }
            dest: "/etc/docker/daemon.json"

  - name: "Restart docker services"
    service:
                name: docker
                state: restarted

  - name: "Changing sysctl file for bridging(1/2)"
    sysctl:
          name: net.bridge.bridge-nf-call-iptables
          value: 1
          sysctl_file: /etc/sysctl.d/k8s.conf
          state: present
          reload: yes

  - name: "Changing sysctl file for bridging(2/2)"
    sysctl:
          name: net.bridge.bridge-nf-call-ip6tables
          value: 1
          sysctl_file: /etc/sysctl.d/k8s.conf
          state: present
          reload: yes

  - name: "Clear Ram caches"
    shell: echo 3 > /proc/sys/vm/drop_caches
                                                 
  - name: Removing previous kubeadm if present
    shell: "echo 'y' | kubeadm reset"

  - name: " Intialize kubeadm"
    shell:
            cmd: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
    register: master_info

  - name: "Describe output of master_node"
    debug:
       var: master_info

  - name: Setting up kubectl for master (1/3)
    file:
          path: ~/.kube
          state: directory

  - name: Setting up kubectl for master (2/3)
    shell: "cp -rf /etc/kubernetes/admin.conf ~/.kube/config"

  - name: Setting up kubectl for master (3/3)
    shell: "chown $(id -u):$(id -g) ~/.kube/config"

  - name: Create overlay network
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Creating token for joining
    command: "kubeadm token create --print-join-command"
    register: token

  - name: Copy the token in a file in master node
    shell: echo "{{ token.stdout }}" > /tmp/token.txt


  - name: Copy token file to controller node
    fetch:
         src: /tmp/token.txt
         dest: "{{ file_path }}token"
         flat: yes

