  - name: "Install docker"
    package:
            name: docker
            state: present
  - name: "Start docker service"
    service:
            name: "docker"
            state: started
            enabled: yes
  
  - name: "Configure yum for k8s"
    yum_repository:
         name: Kubernetes
         description: "RPM of k8s"
         file: kubernetes
         baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
         enabled: yes
         gpgcheck: yes
         gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
         state: present

  - name: "Install kubelet , Kubeadm, kubectl, ip-route"
    package:
            name: "{{ item }}"
            state: present
    loop: 
      - kubectl
      - kubeadm
      - kubelet
      - iproute-tc

  - name: "Start kubelet service"
    service:
            name: "kubelet"
            state: started
            enabled: yes
 
  - name: Changing the docker driver from cgroup to systemd 
    copy:
          content: |
                  {
                    "exec-opts": ["native.cgroupdriver=systemd"]
                  }
          dest: /etc/docker/daemon.json

  - name: "Restart docker services"
    service: 
            name: "docker"
            state: restarted

  - name: "Changing sysctl file for bridging(1/2)"
    sysctl:
          name: net.bridge.bridge-nf-call-iptables
          value: 1
          sysctl_file: /etc/sysctl.d/k8s.conf
          state: present
          reload: yes

  - name: "Changing sysctl file for bridging(2/2)"
    sysctl:
          name: net.bridge.bridge-nf-call-ip6tables
          value: 1
          sysctl_file: /etc/sysctl.d/k8s.conf
          state: present
          reload: yes

  - name: "Clear Ram caches"
    shell: echo 3 > /proc/sys/vm/drop_caches
    
  - name: Copying the token  from localhost to slave
    copy:
          src: "{{ file_path }}token"
          dest: /tmp/token.txt

  - name: Execute the token file so that slave join
    shell: "cat /tmp/token.txt | /usr/bin/bash"
 
